export const UI_PARAMS = {
  refraction: {
    viewWidth: 1000,
    viewHeight: 460,
    baseWavelength: 30,
    omega: 2.8,
    beamSigma: 52,
    sampleWidth: 500,
    sampleHeight: 230,
    normalHalfLen: 60,
    directionMarkerLen: 82,
  },
  prism: {
    raceBaseSpeed: 250,
    mediumSlowdownFactor: 0.75,
    angleSnapDeg: 0.5,
    raceLoopTailSec: 0.8,
    incidentDeg: { min: -15, max: 15, step: 0.5 },
    colorSeparation: { min: 0, max: 14, step: 0.5 },
  },
  raytrace: {
    defaults: {
      sourceXOffset: -250,
      maxDepth: 12,
      minIntensity: 0.001,
      radius: 180,
      nAir: 1,
      nWater: 1.333,
    },
    sourceXOffsetRange: { min: -420, max: 420 },
    maxDepthRange: { min: 2, max: 18 },
    radiusRange: { min: 80, max: 230 },
  },
  droplet: {
    defaults: {
      radius: 160,
      impact: 56,
    },
    radiusRange: { min: 80, max: 240 },
    layoutDefaults: {
      width: 1000,
      height: 560,
      center: { x: 240, y: 190 },
    },
  },
  droplet2: {
    sceneWidth: 1000,
    sceneHeight: 560,
    maxRadius: 60,
    radiusRange: { min: 10, max: 60 },
    raysPerTickRange: { min: 1, max: 4 },
    defaults: {
      radius: 26,
      center: { x: 500, y: 145 },
      step: 0.1,
      raysPerTick: 1,
    },
  },
  rainbow: {
    canvasWidth: 1000,
    canvasHeight: 560,
    defaults: {
      rainIntensity: 0,
      spawnRateAtMax: 10000,
      acceleration: 1.012,
      maxPoints: 10000,
      dropFallSpeed: 150,
      maxActiveDrops: 100000,
    },
    rainIntensityRange: { min: 0, max: 100, step: 1 },
    intensityThreshold: 0.0001,
    intensityMapping: {
      gamma: 0.72,
      compression: 0.8,
      brightnessGain: 1.2,
    },
    manualDropRadius: {
      normal: 6,
      boosted: 7.6,
    },
    previewRadius: 8,
    rainDropRadius: 2.6,
    rainDropLength: 10,
  },
} as const;
