import type { SimulationId } from './registry';

export const UI_TEXT = {
  appTitle: 'Rainbow Simulation',
  appSubtitle: 'Select a module',
  menuButton: 'Menu',
  fallbackTitle: 'Module Unavailable',
  fallbackBody: 'This module is not available in the current build.',
  moduleButtons: {
    refraction: 'Refraction',
    prism: 'Prism',
    raytrace: 'Raytracing',
    droplet: 'Rainbow Angles',
    droplet2: 'Droplet Dispersion',
    rainbow: 'Rainbow',
  } as Record<SimulationId, string>,
  modules: {
    refraction: {
      title: 'Refraction',
      lead: 'Plane wave from the left crossing a sloped interface',
      canvasAria: 'The waves travel slower in a denser medium, leading to a change of direction',
      interfaceAngle: 'Interface angle',
      mediumIndex: 'Medium index n',
    },
    prism: {
      title: 'Blocks and Prism',
      lead: 'Polygon ray tracing with wavelength-dependent indices',
      modeGroupAria: 'Prism mode',
      canvasAria: 'Prism ray tracing visualization',
      clear: 'Clear',
      air: 'Air',
      straight: 'Straight',
      rotated: 'Rotated',
      prism: 'Prism',
      angle: 'Angle',
      colorSeparation: 'Color separation y-offset',
      modeDescriptions: {
        air: 'Vacuum/air mode: all colors travel at light speed, so continue together',
        block_straight: 'Straight block: different colors travel at different speeds, but entry and exit faces are parallel, so direction mostly recovers',
        block_rotated: 'Rotated block: parallel faces still preserve overall direction, with path offsets',
        triangle: 'Triangular prism: non-parallel faces produce visible dispersion between colors',
      },
      legendNPrefix: 'n=',
    },
    raytrace: {
      title: 'Raytracing in a sphere',
      dragHint: 'Drag anywhere to move the source beam',
      lead: 'Ray reflects and refracts through the sphere, no color dispersion in this simulation',
      canvasAria: 'Recursive ray tracing in spherical droplet',
      size: 'Droplet size',
    },
    droplet: {
      title: 'Rainbow angles',
      lead: 'Drag left of center to control the primary beam and right of center for the secondary beam. Click a color to select and toggle its visibility.',
      canvasAria: 'Primary and secondary ray paths in a spherical water droplet',
      rayFamiliesAria: 'Ray families',
      colorFocusAria: 'Color visibility and focus',
      primaryOn: 'Primary ON',
      primaryOff: 'Primary OFF',
      secondaryOn: 'Secondary ON',
      secondaryOff: 'Secondary OFF',
      optimalAngles: 'Set Optimal Angles',
      radius: 'Droplet Radius',
      pxSuffix: 'px',
      focusedColor: 'Controlled color',
      primaryDeflection: 'Primary beam deflection',
      secondaryDeflection: 'Secondary beam deflection',
      notAvailable: 'N/A',
    },
    droplet2: {
      title: 'Light dispersion in a droplet',
      lead: 'White light enters a spherical water droplet and disperses into a rainbow. Turn the single and double reflection on or off. Most of the light passes through.',
      controlsAria: 'Hmmm2',
      canvasAria: 'Hmmm3',
      primaryStart: 'Primary: START',
      primaryClear: 'Primary: CLEAR',
      secondaryStart: 'Secondary: START',
      secondaryClear: 'Secondary: CLEAR',
      radius: 'Droplet Radius',
    },
    rainbow: {
      title: 'Rainbow Simulator',
      lead: 'A droplet gives one colored dot, depending on viewing angle. Place droplets manually or start a rain to see the rainbow form',
      canvasAria: 'Hmmm4',
      startRain: 'Start Rain',
      stopRain: 'Stop Rain',
      clear: 'Clear',
      drops: 'Drops',
      rate: 'Rate',
      manualInput: 'Manual input',
      manualHint: 'Drag preview, release to stamp',
      frameSuffix: '/frame',
    },
  },
};
